#!/usr/bin/env php
<?php

/**
 * Declare paths
 */
$basePath = realpath(__DIR__ . '/..');
$dataPath = $basePath . '/surume-data';

/**
 * Include autoloader & dependencies
 */
require $basePath . '/vendor/autoload.php';
require $dataPath . '/autorun/autorun.php5.polyfill';

use Surume\Loop\Loop;

$loop = new Loop(
    new \Surume\Loop\Model\StreamSelectLoop()
);

$start = microtime(true);

for ($i=0; $i<1e5; ++$i)
{
    $loop->afterTick(function() {});
}

$loop->afterTick(function() use($loop) {
    $loop->stop();
});

$loop->start();

$end = microtime(true);

var_dump(($end-$start));