#!/usr/bin/env php
<?php

/**
 * Declare paths
 */
$basePath = realpath(__DIR__ . '/..');
$dataPath = $basePath . '/surume-data';

/**
 * Include autoloader & dependencies
 */
require $basePath . '/vendor/autoload.php';
require $dataPath . '/autorun/autorun.php5.polyfill';

use Surume\Event\BaseEventEmitter;

$event = new BaseEventEmitter();
$event->on('event', function() {});

$start = microtime(true);

for ($i=0; $i<1e6; ++$i)
{
    $event->emit('event');
}

$end = microtime(true);

var_dump(($end-$start));